### ISSUE TITLE
Use a hash for reference/alternate_bases when making the merge key

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#102]
We currently just concatenate reference/alternate_bases together as the merge key (see [here](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/gcp_variant_transforms/libs/variant_merge/move_to_calls_strategy.py#L120)).

This may break Dataflow if the length of reference/alternate_bases are large (larger than 1MB limit for the key). We should create a hash of these fields and use that instead. This ensures that our keys do not get arbitrarily large.

As a result, the key would be `reference_name:start_position:end_position:<hash of reference_name:alternate_bases>`. Given that we include reference/start/end as part of the key (excluding the hash) then the risk of collision is extremely low. However, we can still add an assert [here](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/gcp_variant_transforms/libs/variant_merge/move_to_calls_strategy.py#L99) just to be sure.

**Comment by nmousavi** [comment]
Also: this is currently an issue when using server based shuffle in Dataflow.
