### ISSUE TITLE
Add documentation on how to run the pipeline in a particular zone/region

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#115]
There is both region [1] and zone arguments (and in two places! one in the pipelines API and one in the Dataflow API). We should document how to use these features.

[1] https://cloud.google.com/dataflow/docs/concepts/regional-endpoints#supported_regional_endpoints

**Comment by smrgit** [comment]
on a related note, I noticed recently when running a couple of variant transforms tasks that the "harness" VMs were running in us-central1-b, for example, while the associated ggp VMs were running in us-west1-a (which is one of the zones that had been passed in using the --zones option in the "gcloud alpha genomics pipelines run" command) -- I'm kind of assuming that the "harness" VM is actually doing very little work and is no data is moving to or from it, so maybe it doesn't matter at all where that VM lives(?) but it still seemed a bit odd to see that on the console ...
