### ISSUE TITLE
Cast Number=A/G/R fields to a list in FORMAT fields

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#122]
We currently [cast Number=. fields to a list](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/gcp_variant_transforms/beam_io/vcfio.py#L861) for FORMAT fields. We should do the same for Number=A/G/R fields.

This is blocking imports on Issue #119.

Note: ultimately, the schema checks (Issue #101), will fix the schema errors, but I still think it makes sense to always return a list natively for Number=A/G/R fields as they should be the same logic as INFO fields (this is also done by PyVCF).

**Comment by nmousavi** [comment]
New image with fix PR #123  is released.
