### ISSUE TITLE
option to allow number=A fields with too few values

### ISSUE THREAD

**Issue by snarfed** [googlegenomics/gcp-variant-transforms#129]
we currently have a couple `number=A` INFO fields in our VCFs that often only have one value. right now, VT's validation is strict and doesn't allow these. it's right, of course, and we should either fix them or remove them from our VCFs...

...but in the meantime, i've been using a small hack to allow these, and put the value in just the first allele (again, incorrect, i know :P): https://github.com/snarfed/gcp-variant-transforms/commit/1aa4f4fcf0ad7869410f0c7aa265133ffbecfb17 . it's from before parts of `bigquery_vcf_schema.py` were refactored into `processed_variant.py` (cc @bashir2).

would you all consider maybe allowing this, or doing something similar, with a flag? maybe with `--allow_malformed_records`? i'm open to alternatives.

**Comment by snarfed** [comment]
(#79 and #101 are related)

**Comment by bashir2** [comment]
Have you considered using the [--representative_header_file](https://github.com/googlegenomics/gcp-variant-transforms/blob/4f498ad0559d6728eea3fc2b9daae78f7908349f/gcp_variant_transforms/options/variant_transform_options.py#L68) option. It seems to me that you can fix this problem by providing a VCF header that has `Number=1` for those INFO fields. With this solution the field will be correctly added to non-allele INFO fields as well.

**Comment by snarfed** [comment]
good point! that could definitely work, at least for now. we actually already use it, i just didn't think to change its `Number=` for these fields. eventually we'd like to stop using a representative VCF file, though, so we can add new fields as in #83.
