### ISSUE TITLE
No error, but resulting table doesn't work

### ISSUE THREAD

**Issue by andrewelamb** [googlegenomics/gcp-variant-transforms#140]
Hello,

I have a set of VCF's that get made into bigquery tables, without error, but aren't working in bigquery.

The resulting schema looks like:

reference_name | STRING | NULLABLE | Reference name.
-- | -- | -- | --
start_position | INTEGER | NULLABLE | Start position (0-based). Corresponds to the first base of the string of reference bases.
end_position | INTEGER | NULLABLE | End position (0-based). Corresponds to the first base after the last base in the reference allele.
reference_bases | STRING | NULLABLE | Reference bases.
alternate_bases | RECORD | REPEATED | One record for each alternate base (if any).
alternate_bases.alt | STRING | NULLABLE | Alternate base.
names | STRING | REPEATED | Variant names (e.g. RefSNP ID).
quality | FLOAT | NULLABLE | Phred-scaled quality score (-10log10 prob(call is wrong)). Higher values imply better quality.
filter | STRING | REPEATED | List of failed filters (if any) or "PASS" indicating the variant has passed all filters.
call | RECORD | REPEATED | One record for each call.
call.name | STRING | NULLABLE | Name of the call.
call.genotype | INTEGER | REPEATED | Genotype of the call. "-1" is used in cases where the genotype is not called.
call.phaseset | STRING | NULLABLE | Phaseset of the call (if any). "*" is used in cases where the genotype is phased, but no phase set ("PS" in FORMAT) was specified.
call.GQ | INTEGER | NULLABLE | Genotype Quality
call.SP | INTEGER | NULLABLE | Phred-scaled strand bias P-value
call.PL | INTEGER | REPEATED | List of Phred-scaled genotype likelihoods
call.DV | INTEGER | NULLABLE | # high-quality non-reference bases
call.GL | FLOAT | REPEATED | Likelihoods for RR,RA,AA genotypes (R=ref,A=alt)
call.DP | INTEGER | NULLABLE | # high-quality bases

But the details show no data:

Table ID | neoepitopes:r1_sorted_variants.eagle_1_TESLA_sorted
-- | --
Table Size | 0 B
Number of Rows | 0

What's the best way of troubleshooting this?

**Comment by arostamianfar** [comment]
Questions:
- Did you run the pipeline with `--runner DataflowRunner`? Otherwise, it uses DirectRunner, which for some reason does not immediately update the table summary page (it takes an hour or so). You can, however, query the table immediately and you should see the results.
- Did you run with `--allow_malformed_records`? It is possible that all records were considered "malformed" by the pipeline. You can look at the logs to see the records that were ignored. If using DataflowRunner, you can navigate to the [Dataflow Console](https://console.cloud.google.com/dataflow) and click on "FilterVariants" step and see whether there are any warning logs about records being ignored.

**Comment by andrewelamb** [comment]
I did use --runner DataflowRunner, and --allow_malformed_records. I did run this a few eeks ago, so that shouldn't be an issue. It's more likely it seems to me that all the records are malformed, I've had a lot of issues with these particular vcf files so far.

It does look like there are a bunch of errors, is it obvious what the issue is?

 2018-03-15 (12:01:53) VCF record read failed in gs://r1_debugged_sorted_variants_syn11811333/eagle_2_TESLA_sorted.vcf for ...
VCF record read failed in gs://r1_debugged_sorted_variants_syn11811333/eagle_2_TESLA_sorted.vcf for line 11	<edited out> GT:PL:GQ	DP=121;VDB=1.444697e-01;RPB=2.266192e-01;AF1=0.5;AC1=1;DP4=22,21,24,21;MQ=60;FQ=225;PV4=1,1,1,1;ACGTNacgtnPLUS=10,0,12,0,0,15,0,13,0,0;ACGTNacgtnMINUS=16,0,10,0,0,20,0,19,0,0	DP=189;DP5=79,100,0,0,1;DP5all=84,103,0,0,2;ACGTNacgtnHQ=0,1,79,0,0,0,0,100,0,0;ACGTNacgtn=0,1,84,0,0,0,1,103,0,0;VAF=0.00;TSR=0;PBINOM=6.52530446799857e-55.
timestamp
2018-03-15T19:01:53.199592113Z
logger
root:filter_variants.py:_is_valid_record
severity
WARNING
worker
eagle2teslasorted-03151157-4bd6-harness-v7k6
step
FilterVariants/ApplyFilters
thread
239:140370905691904




From the console:

Step summary
Step name
FilterVariants
Wall time
0 sec
Input collections
ReadFromVcf/Read.out0
Elements added
837
Estimated size
590.97 KB
Output collections
FilterVariants/ApplyFilters.out0
Elements added
0
Estimated size
–

**Comment by arostamianfar** [comment]
Thanks for providing the details! yes, it looks like everything was filtered ("elements added" is zero after filter). Unfortunately, I just noticed that we don't log the error (filed Issue #144), but since the file is small, you can try rerunning without --allow_malformed_record to see what the error is (the pipeline will fail in this case though). Is it the same issue as the 'float' vs 'integer' issue from #119? 
Could you please confirm whether `VDB`, `RPB`, and `PBINOM` are defined as Float in the header?

P.S. we are making progress on making Variant Transforms more robust by inferring header types and dynamically resolving these type conflicts, which should enable your files to be loaded seamlessly. Please see our [design doc](https://docs.google.com/document/d/1JusaPllbpXynNziNzdyOdSRTM8i7UXbNvtkbrWNMq3Q/edit#) and feel free to make comments. (@nmousavi FYI).

**Comment by andrewelamb** [comment]
So, it looks like PBINOM, is missing from the header, VDB and RPB are defined as floats however. I'll try adding this and see if it works, if not Ill run without --allow_malformed_record and see what the error is.

**Comment by arostamianfar** [comment]
Thanks for the update. To clarify: are VDB and RPB defined properly in the header as well? If so, they should be visible in the BigQuery schema (the schema doesn't include the fields).
Would it possible for you to provide just a few lines of the VCF file (header + a few records)? You may replace sensitive fields with dummy values. We are very curious why the error is happening and may be easier for us to debug if we had access to a similarly formatted data.

**Comment by andrewelamb** [comment]
Sure, after going back through the vcfs I also noticed that columns were not in the same order as all my other vcfs, so I fixed this as well. Here's an example header and few lines after fixing:

##fileformat=VCFv4.1
##samtoolsVersion=0.1.19-44428cd
##reference=file:///icgc/ngs_share/assemblies/hg19_GRCh37_1000genomes/sequence/1KGRef/hs37d5.fa
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
##contig=<ID=GL000207.1,length=4262>
##contig=<ID=GL000226.1,length=15008>
##contig=<ID=GL000229.1,length=19913>
##contig=<ID=GL000231.1,length=27386>
##contig=<ID=GL000210.1,length=27682>
##contig=<ID=GL000239.1,length=33824>
##contig=<ID=GL000235.1,length=34474>
##contig=<ID=GL000201.1,length=36148>
##contig=<ID=GL000247.1,length=36422>
##contig=<ID=GL000245.1,length=36651>
##contig=<ID=GL000197.1,length=37175>
##contig=<ID=GL000203.1,length=37498>
##contig=<ID=GL000246.1,length=38154>
##contig=<ID=GL000249.1,length=38502>
##contig=<ID=GL000196.1,length=38914>
##contig=<ID=GL000248.1,length=39786>
##contig=<ID=GL000244.1,length=39929>
##contig=<ID=GL000238.1,length=39939>
##contig=<ID=GL000202.1,length=40103>
##contig=<ID=GL000234.1,length=40531>
##contig=<ID=GL000232.1,length=40652>
##contig=<ID=GL000206.1,length=41001>
##contig=<ID=GL000240.1,length=41933>
##contig=<ID=GL000236.1,length=41934>
##contig=<ID=GL000241.1,length=42152>
##contig=<ID=GL000243.1,length=43341>
##contig=<ID=GL000242.1,length=43523>
##contig=<ID=GL000230.1,length=43691>
##contig=<ID=GL000237.1,length=45867>
##contig=<ID=GL000233.1,length=45941>
##contig=<ID=GL000204.1,length=81310>
##contig=<ID=GL000198.1,length=90085>
##contig=<ID=GL000208.1,length=92689>
##contig=<ID=GL000191.1,length=106433>
##contig=<ID=GL000227.1,length=128374>
##contig=<ID=GL000228.1,length=129120>
##contig=<ID=GL000214.1,length=137718>
##contig=<ID=GL000221.1,length=155397>
##contig=<ID=GL000209.1,length=159169>
##contig=<ID=GL000218.1,length=161147>
##contig=<ID=GL000220.1,length=161802>
##contig=<ID=GL000213.1,length=164239>
##contig=<ID=GL000211.1,length=166566>
##contig=<ID=GL000199.1,length=169874>
##contig=<ID=GL000217.1,length=172149>
##contig=<ID=GL000216.1,length=172294>
##contig=<ID=GL000215.1,length=172545>
##contig=<ID=GL000205.1,length=174588>
##contig=<ID=GL000219.1,length=179198>
##contig=<ID=GL000224.1,length=179693>
##contig=<ID=GL000223.1,length=180455>
##contig=<ID=GL000195.1,length=182896>
##contig=<ID=GL000212.1,length=186858>
##contig=<ID=GL000222.1,length=186861>
##contig=<ID=GL000200.1,length=187035>
##contig=<ID=GL000193.1,length=189789>
##contig=<ID=GL000194.1,length=191469>
##contig=<ID=GL000225.1,length=211173>
##contig=<ID=GL000192.1,length=547496>
##contig=<ID=NC_007605,length=171823>
##contig=<ID=hs37d5,length=35477943>
##TUMOR=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
##TUMOR=<ID=DP4,Number=4,Type=Integer,Description="# high-quality ref-forward bases, ref-reverse, alt-forward and alt-reverse bases">
##TUMOR=<ID=MQ,Number=1,Type=Integer,Description="Root-mean-square mapping quality of covering reads">
##TUMOR=<ID=FQ,Number=1,Type=Float,Description="Phred probability of all samples being the same">
##TUMOR=<ID=AF1,Number=1,Type=Float,Description="Max-likelihood estimate of the first ALT allele frequency (assuming HWE)">
##TUMOR=<ID=AC1,Number=1,Type=Float,Description="Max-likelihood estimate of the first ALT allele count (no HWE assumption)">
##TUMOR=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##TUMOR=<ID=IS,Number=2,Type=Float,Description="Maximum number of reads supporting an indel and fraction of indel reads">
##TUMOR=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">
##TUMOR=<ID=G3,Number=3,Type=Float,Description="ML estimate of genotype frequencies">
##TUMOR=<ID=HWE,Number=1,Type=Float,Description="Chi^2 based HWE test P-value based on G3">
##TUMOR=<ID=CLR,Number=1,Type=Integer,Description="Log ratio of genotype likelihoods with and without the constraint">
##TUMOR=<ID=UGT,Number=1,Type=String,Description="The most probable unconstrained genotype configuration in the trio">
##TUMOR=<ID=CGT,Number=1,Type=String,Description="The most probable constrained genotype configuration in the trio">
##TUMOR=<ID=PV4,Number=4,Type=Float,Description="P-values for strand bias, baseQ bias, mapQ bias and tail distance bias">
##TUMOR=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##TUMOR=<ID=PC2,Number=2,Type=Integer,Description="Phred probability of the nonRef allele frequency in group1 samples being larger (,smaller) than in group2.">
##TUMOR=<ID=PCHI2,Number=1,Type=Float,Description="Posterior weighted chi^2 P-value for testing the association between group1 and group2 samples.">
##TUMOR=<ID=QCHI2,Number=1,Type=Integer,Description="Phred scaled PCHI2.">
##TUMOR=<ID=PR,Number=1,Type=Integer,Description="# permutations yielding a smaller PCHI2.">
##TUMOR=<ID=QBD,Number=1,Type=Float,Description="Quality by Depth: QUAL/#reads">
##TUMOR=<ID=RPB,Number=1,Type=Float,Description="Read Position Bias">
##TUMOR=<ID=MDV,Number=1,Type=Integer,Description="Maximum number of high-quality nonRef reads in samples">
##TUMOR=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias (v2) for filtering splice-site artefacts in RNA-seq data. Note: this version may be broken.">
##TUMOR=<ID=PBINOM,Number=1,Type=Float,Description="?">
##NORMAL=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
##NORMAL=<ID=DP4,Number=4,Type=Integer,Description="# high-quality ref-forward bases, ref-reverse, alt-forward and alt-reverse bases">
##NORMAL=<ID=MQ,Number=1,Type=Integer,Description="Root-mean-square mapping quality of covering reads">
##NORMAL=<ID=FQ,Number=1,Type=Float,Description="Phred probability of all samples being the same">
##NORMAL=<ID=AF1,Number=1,Type=Float,Description="Max-likelihood estimate of the first ALT allele frequency (assuming HWE)">
##NORMAL=<ID=AC1,Number=1,Type=Float,Description="Max-likelihood estimate of the first ALT allele count (no HWE assumption)">
##NORMAL=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##NORMAL=<ID=IS,Number=2,Type=Float,Description="Maximum number of reads supporting an indel and fraction of indel reads">
##NORMAL=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">
##NORMAL=<ID=G3,Number=3,Type=Float,Description="ML estimate of genotype frequencies">
##NORMAL=<ID=HWE,Number=1,Type=Float,Description="Chi^2 based HWE test P-value based on G3">
##NORMAL=<ID=CLR,Number=1,Type=Integer,Description="Log ratio of genotype likelihoods with and without the constraint">
##NORMAL=<ID=UGT,Number=1,Type=String,Description="The most probable unconstrained genotype configuration in the trio">
##NORMAL=<ID=CGT,Number=1,Type=String,Description="The most probable constrained genotype configuration in the trio">
##NORMAL=<ID=PV4,Number=4,Type=Float,Description="P-values for strand bias, baseQ bias, mapQ bias and tail distance bias">
##NORMAL=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##NORMAL=<ID=PC2,Number=2,Type=Integer,Description="Phred probability of the nonRef allele frequency in group1 samples being larger (,smaller) than in group2.">
##NORMAL=<ID=PCHI2,Number=1,Type=Float,Description="Posterior weighted chi^2 P-value for testing the association between group1 and group2 samples.">
##NORMAL=<ID=QCHI2,Number=1,Type=Integer,Description="Phred scaled PCHI2.">
##NORMAL=<ID=PR,Number=1,Type=Integer,Description="# permutations yielding a smaller PCHI2.">
##NORMAL=<ID=QBD,Number=1,Type=Float,Description="Quality by Depth: QUAL/#reads">
##NORMAL=<ID=RPB,Number=1,Type=Float,Description="Read Position Bias">
##NORMAL=<ID=MDV,Number=1,Type=Integer,Description="Maximum number of high-quality nonRef reads in samples">
##NORMAL=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias (v2) for filtering splice-site artefacts in RNA-seq data. Note: this version may be broken.">
##NORMAL=<ID=PBINOM,Number=1,Type=Float,Description="?">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Likelihoods for RR,RA,AA genotypes (R=ref,A=alt)">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="# high-quality bases">
##FORMAT=<ID=DV,Number=1,Type=Integer,Description="# high-quality non-reference bases">
##FORMAT=<ID=SP,Number=1,Type=Integer,Description="Phred-scaled strand bias P-value">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
##Liftover=GRCh38
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR	NORMAL
x	x	x	x	x	210	PASS	.	GT:PL:GQ	DP=245;VDB=4.073709e-01;RPB=3.592296e-01;AF1=0.5;AC1=1;DP4=98,35,35,10;MQ=60;FQ=213;PV4=1,1,1,1;ACGTNacgtnPLUS=0,40,0,18,0,0,28,0,12,0;ACGTNacgtnMINUS=0,58,0,17,0,0,46,0,16,0	DP=256;DP5=142,107,0,0,0;DP5all=145,111,0,0,0;ACGTNacgtnHQ=0,142,0,0,0,0,107,0,0,0;ACGTNacgtn=0,145,0,0,0,0,111,0,0,0;VAF=0.00;TSR=0;PBINOM=1.10542957505211e-75
x	x	x	x	x	225	PASS	.	GT:PL:GQ	DP=330;VDB=7.020888e-02;RPB=-5.294533e-01;AF1=0.5;AC1=1;DP4=70,40,91,23;MQ=60;FQ=225;PV4=0.069,1,1,1;ACGTNacgtnPLUS=46,0,39,0,0,30,0,26,1,0;ACGTNacgtnMINUS=49,0,31,0,0,39,0,43,0,0	DP=313;DP5=142,145,0,0,0;DP5all=156,156,0,0,1;ACGTNacgtnHQ=0,0,142,0,0,0,0,145,0,0;ACGTNacgtn=0,0,156,0,0,0,0,156,1,0;VAF=0.00;TSR=0;PBINOM=4.02152936677193e-87

**Comment by andrewelamb** [comment]
So it looks like adding the PBINOM header and reordering the column headers didn't fix this issue, I'll rerun without --allow_malformed_record

**Comment by arostamianfar** [comment]
Thanks for providing the example! I now know what's going on :)

The format of the VCF file is pretty strange and, as far as I can tell, is not compatible with the [VCF spec](http://samtools.github.io/hts-specs/VCFv4.3.pdf). Particularly, the fields under TUMOR and NORMAL must conform with the spec defined by FORMAT (i.e. given that the format is defined as `GT:PL:GQ` the value must be something like `0/0:1,2,3:200`). However, the provided values are more like INFO fields (with `=` signs).
The definition of the fields are defined under `NORMAL` and `TUMOR` in the header (using `##NORMAL` and `##TUMOR`) and these are not standard VCF representations, which are basically ignored by the parser. In short, we are unfortunately not able to parse the VCF file in this format.

The current solution is to rewrite the VCF file to conform to the spec, which essentially means rewriting the header and the fields as:
- The header fields with `##TUMOR` and `##NORMAL` should be replaced with `##FORMAT`.
- The FORMAT field should be rewritten to contain actual keys (i.e. instead of `GT:PL:GQ` it should be `DP:VDP:RPB:...`).
- The data for each sample must be formatted to replace `key=value` with just `value` (the key is defined under FORMAT).

Questions:
- Would it be possible to let us know which tool was used to generate the VCF files?
- Are you aware of a spec that defines VCF files in this manner? We have not seen VCF files like this so far, so I'm wondering if it's a customization on the spec that we are not aware of.

@deflaux and @mbookman in case they have seen this format before.

**Comment by andrewelamb** [comment]
So to give some background we're running a kaggle-like challenge:

http://dreamchallenges.org/sagesynapse/

The participants don't have to provide their pipeline details, but some did. I can see if this team was one of those. These are from the first round where we didn't set any rules on the submitted vcfs, but we've since imposed some requirements that solved most of these issues.

**Comment by andrewelamb** [comment]
Here are the errors I'm getting running without --allow_malformed_record:

[1] "ValueError: Invalid record in VCF file. Error: invalid literal for int() with base 10: 'DP=245;VDB=4.073709e-01;RPB=3.592296e-01;AF1=0.5;AC1=1;DP4=98,35,35,10;MQ=60;FQ=213;PV4=1,1,1,1;ACGTNacgtnPLUS=0,40,0,18,0,0,28,0,12,0;ACGTNacgtnMINUS=0,58,0,17,0,0,46,0,16,0'"    
[2] "ValueError: Invalid record in VCF file. Error: invalid literal for int() with base 10: 'DP=148;VDB=1.892723e-01;RPB=2.858800e-01;AF1=0.5;AC1=1;DP4=59,11,26,5;MQ=60;FQ=225;PV4=0.85,1,1,0.036;ACGTNacgtnPLUS=15,0,28,0,0,9,0,21,0,0;ACGTNacgtnMINUS=11,0,31,0,0,6,0,22,0,0'"
[3] "ValueError: Invalid record in VCF file. Error: invalid literal for int() with base 10: 'DP=2456;VDB=1.682483e-01;AF1=1;AC1=2;DP4=0,0,1104,412;MQ=60;FQ=-282;ACGTNacgtnPLUS=0,0,0,0,0,0,0,0,0,0;ACGTNacgtnMINUS=1109,0,0,0,0,1305,0,0,0,0'"                                  
[4] "ValueError: Invalid record in VCF file. Error: invalid literal for int() with base 10: 'DP=190;VDB=1.407824e-01;RPB=-9.604686e-01;AF1=0;AC1=0;DP4=97,23,8,2;MQ=60;FQ=-134;PV4=0.79,1,1,0.41;ACGTNacgtnPLUS=5,0,54,0,0,3,0,39,0,0;ACGTNacgtnMINUS=3,0,43,0,0,4,0,32,0,0'"

**Comment by arostamianfar** [comment]
I see. Yes, these failures are expected as the parser is trying to parse the "GT" field (which should be a list of integers) and is finding the long string with `DP=...`.

Unfortunately, I can't see any way to load these VCF files to BigQuery without reformatting them to conform to the spec. And since it doesn't look like there is even a spec for this type of VCF, we can't change our parser to load it.

You may use the VCF validator tool to ensure the VCF files are valid: https://github.com/ebivariation/vcf-validator

**Comment by arostamianfar** [comment]
To add: if you decide to write a script to reformat the VCF files, you can use [dsub](https://github.com/googlegenomics/dsub/tree/master/examples/custom_scripts) to run pipelines in parallel if you have a large number of these files.
