### ISSUE TITLE
Fix integration testing failures

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#151]
Our integration testing started failing since PR #148 with error [1]. I believe it may be b/c the test pushes the runtime above 30 minutes, which causes the oauth token to get expired.

Solutions:
- (short term): Reduce the # of files in this test to be 10k (i.e. just under "valid-10000-copies-1/"). This should push the test to run under 20mins, and we can verify whether it fixes the issue.
- Investigate how to either increase the token expiration time and/or catch the exception.

[1]
```
google.auth.exceptions.RefreshError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/542668135037@cloudbuild.gserviceaccount.com/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Response:\n404 page not found\n', <google.auth.transport.requests._Response object at 0x7f7504072c90>)
```

**Comment by pgrosu** [comment]
Hi Asha,

Why not try to integrate with the internal Jenkins (Kororo) as the [protobuf transitioned to it](https://github.com/google/protobuf/tree/master/kokoro) in order to get around this and other resource problems?  It has github integration to trigger automatic testing for new PRs or updated commits.

~p

**Comment by arostamianfar** [comment]
Hi Paul,

I think Kokoro is great for cases where is an equivalent source under google internal repo. Given that we build everything in open source, then that is not an option for us (unless we add a sync from github to internal repo). Other than this strange issue, I actually think our existing integration testing framework is working very well.

We are actually discussing if we want to make the continuous runs smaller (<20mins) to avoid this bug and essentially migrate some tests to "huge" so that they are only run for release candidates.

**Comment by pgrosu** [comment]
Hi Asha,

I didn't realize you needed to duplicate the code with Kororo, though that could be automated.  In any case, if it's just an issue with refreshing the token, that is pretty easy.  I'm not sure what the programming language you use, but see the following previous posts/docs for how to use `setAccessToken()` and `setRefreshToken()`:

https://github.com/googlegenomics/utils-java/issues/8

https://developers.google.com/identity/protocols/OAuth2WebServer#offline

Regarding the timeout I thought you could specify a [`travis_wait` amount (in minutes)](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out).  When you mean "huge" are you saying that you have a customized build environment, that is different that the following standard ones:

https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

Paul

**Comment by bashir2** [comment]
@pgrosu just to clarify: This is not a Travis timeout issue. These tests are not even triggered by Travis but instead are implemented using [Container Registry Build Triggers](https://cloud.google.com/container-builder/docs/running-builds/automate-builds); for a little more, please details check [here](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/development_guide.md#continuous-integration).

**Comment by pgrosu** [comment]
Hi Bashir (@bashir2),

Many thanks for the clarification - now it makes more sense! 

Asha (@arostamianfar), if you are planning to bound your CI only to <20min by limiting your test scenarios, you might miss the regressions that [Bashir mentioned in PR 132](https://github.com/googlegenomics/gcp-variant-transforms/pull/132#discussion_r173365240) he would like to catch - including any variations in performance.  Why not scale up your pipeline to more workers?  I thought [Bashir got them down to ~19 min](https://github.com/googlegenomics/gcp-variant-transforms/pull/132#discussion_r173344866), though maybe that's only for the Platinum Genomes dataset.

Paul

**Comment by arostamianfar** [comment]
@pgrosu: actually, the 20min time limit turned out to be a red herring as the tests are still failing even after Allie rolled back her change. We're still investigating what has changed in one of our dependencies that causes the oauth refresh process to fail.

**Comment by pgrosu** [comment]
@arostamianfar For which most-recent PR did it last work properly?

**Comment by arostamianfar** [comment]
Update: it turns out that this is apparently a bug in the CloudBuild code that recently surfaced and it's not related to our code. They only accept "default" as the service account and not "email" (e.g. "service-accounts/default" is good but "service-accounts/542668135037" is not). Waiting for a release on their end to see if it fixes the issue (ETA tomorrow).

**Comment by arostamianfar** [comment]
Integration tests are now passing!
