### ISSUE TITLE
Re-import gnomAD with the new annotation options in VT

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#187]
We currently host gnomAD as part of the annotation offering, but we can present a much better BQ table using the new VT features (`--annotation_fields`). We should re-annotation and re-import gnomAD using VT.

**Comment by bashir2** [comment]
Copied the previously mentioned table to `bigquery-public-data.human_variant_annotation.gnomad_gnomad_genomes_hg19_release_2_0_2`. Updated some annotation field descriptions from [VEP documentation](https://useast.ensembl.org/info/docs/tools/vep/vep_formats.html). Sample query:
```SQL
#standardSQL
SELECT COUNT(0)
FROM `bigquery-public-data.human_variant_annotation.gnomad_gnomad_genomes_hg19_release_2_0_2`
```
which returns
```
241056551
```
