### ISSUE TITLE
Unrecognized flags should stop the execution early.

### ISSUE THREAD

**Issue by bashir2** [googlegenomics/gcp-variant-transforms#205]
Currently, because some of the arguments are Beam specific, we do not fail on unrecognized flags. But we should check the remaining flags and if there is any that is not recognized by Beam either, then we should fail the execution early and point out the error to the user.

**Comment by arostamianfar** [comment]
Bumping up the priority as users have been hit by this issue multiple times (e.g. typo in the flag names).
