### ISSUE TITLE
Proper handling of "inf" float values.

### ISSUE THREAD

**Issue by bashir2** [googlegenomics/gcp-variant-transforms#219]
Context: [this thread](https://groups.google.com/d/topic/google-genomics-discuss/bdvpLwDzcJ8/discussion).

In [bigquery_util._get_bigquery_sanitized_float](https://github.com/googlegenomics/gcp-variant-transforms/blob/c4659bba2cf577d64f15db5cd9f477d9ea2b51b0/gcp_variant_transforms/libs/bigquery_util.py#L213) when a float value is `inf`, it is being converted to `maxint` which in turn causes [this ValueError exception](https://github.com/googlegenomics/gcp-variant-transforms/blob/c4659bba2cf577d64f15db5cd9f477d9ea2b51b0/gcp_variant_transforms/libs/bigquery_row_generator.py#L202).

This can be avoided by using `--allow_incompatible_records` which causes another cast to float but I think this is a regression that was introduced as an unintentional consequence of [this commit](https://github.com/googlegenomics/gcp-variant-transforms/pull/146/files#diff-674d337e04318e6ee1252a280a22b7f9L256).

In the gnomAD dataset, some of the float fields are "Infinity" and that is what triggered this investigation (note `float('inf') == float('Infinity')`)

**Comment by nmousavi** [comment]
I think we should convert 'inf' to float(maxint) in the first place as 'inf' is used for float type (at least in python).

This issue brings up a good question: should VariantTransform complain about type mismatches that BigQuery doesn't care (e.g., int vs float)? Perhaps No. I think we should: 
1) First modify the code to convert  'inf' to float(sys.maxint) instead. This is enough for the issue referenced in the [context](https://groups.google.com/forum/#!topic/google-genomics-discuss/bdvpLwDzcJ8/discussion).
2) Modify VT to not complain about 'int' vs 'float' mismatch (assuming answer to the above question is NO)

**Comment by nmousavi** [comment]
1) Hmm, I don't like setting some arbitrary large number. Apart from possible collision with some valid value, one has to look into VT code to make sense of this value. We should ideally pick a large number that has a meaning in BigQuery too (worth looking into BQ IS_INF() function). At the very least,  sys.float_info.max or float(maxint) are good options as one can verify them in python (no need to read our code).

2) Fair, if you think int-float conversion is not benign, then it's good reason to keep it as is. My only concern is that users have to use the flag for int vs float case, and may not realize/pay attention it has a broader impact (i.e. resolving other mismatches), hence proposing resolving benign mismatches by default. 
2.1) Yes, both PyVcf and BQ do the conversion. :-)

**Comment by bashir2** [comment]
Thanks folks for your comments.

Re. max value, I do not have any strong preference but I agree that picking an arbitrary number defined in our code is not a great idea.

Re. `float(val) == val` check and exception, what we need to make sure is that "sanitization" functions do not change the _type_ of values returned; that's the problem with `_get_bigquery_sanitized_float`, which is fixed in PR #220.

After this fix, I think the only way of getting int vs float discrepancy is when one field is defined as Integer in one VCF and the same field is Float in another (is my understanding correct?), in which case I think it is a good idea to be explicit and fail unless `--allow_incompatible_records` is set.
