### ISSUE TITLE
Add ability to run a single integration test

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#229]
Currently, the only options are: run small tests, run presubmit tests, or run all tests. Would be nice to add the ability to run a particular test when we want to debug one failing test.

**Comment by bashir2** [comment]
+1 to the feature. In the meantime, if anyone needs to do this, here is [the line to edit](https://github.com/googlegenomics/gcp-variant-transforms/blob/3dad134166b099a8606d93e966c5ebf77daec16d/gcp_variant_transforms/testing/integration/run_tests.py#L314) and limit the files to the ones you want. Please also note the [--keep_tables](https://github.com/googlegenomics/gcp-variant-transforms/blob/3dad134166b099a8606d93e966c5ebf77daec16d/gcp_variant_transforms/testing/integration/run_tests.py#L294) and [--revalidation_dataset_id](https://github.com/googlegenomics/gcp-variant-transforms/blob/3dad134166b099a8606d93e966c5ebf77daec16d/gcp_variant_transforms/testing/integration/run_tests.py#L297) options which can speed up testing if you are changing queries only.
