### ISSUE TITLE
Catch more errors with the validator/preprocessor tool

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#258]
The preprocessor tool currently catches VCF parsing errors, header mismatch errors, and undefined header errors. There are a few other errors that would be ideal to catch. Particularly:
- Header definition mismatch errors (e.g. header is defined as integer, but a float value is provided). This should ideally result in changing the recommendation for the field with the mismatch. 
- Alternate allele errors: catch cases where Number=A INFO values do not have the same cardinality as alternate bases.

**Comment by allieychen** [comment]
The two types of mismatches listed above are added into the report by running the preprocessor tool with the flag `--report_all_conflicts`. The related fields and suggested resolutions are listed in `Inferred Headers` category. Please refer to [VCF files preprocessor doc](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/vcf_files_preprocessor.md) for more details.
