### ISSUE TITLE
Invalid command in documentation on running jobs

### ISSUE THREAD

**Issue by slagelwa** [googlegenomics/gcp-variant-transforms#275]
In the document, '[Running jobs in a particular region/zone](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/running_in_particular_zone_region.md)', the command stated: 

```
gcloud alpha genomics pipelines run ... \
    --regions europe-west1 \
    --zones europe-west1-b
```

Returns the error:

`ERROR: (gcloud.alpha.genomics.pipelines.run) INVALID_ARGUMENT: Error: validating pipeline: zones and regions cannot be specified together`

**Comment by arostamianfar** [comment]
Thank you for filing this! We'll update the docs soon.
