### ISSUE TITLE
Remove the constrains (<=2.4) on beam version

### ISSUE THREAD

**Issue by allieychen** [googlegenomics/gcp-variant-transforms#291]
The latest Apache Beam (2.5) has some issues on directRunner, which fails our integration tests. A temporary fix was made through  [PR 284](https://github.com/googlegenomics/gcp-variant-transforms/pull/284/files). Once they release the next version, revert the PR and make sure the build works fine.

**Comment by arostamianfar** [comment]
Beam 2.6.0 is released! yay! Allie, could you please run our integration tests with 2.6.0 and see whether we can remove the constraint on 2.4.0?

**Comment by allieychen** [comment]
The pipeline still fails after updating to 2.6.0. It shows the same error message as in [BEAM 4755](https://issues.apache.org/jira/browse/BEAM-4755?jql=project%20%3D%20BEAM%20AND%20text%20~%20%22Python%20cast%22).

**Comment by pgrosu** [comment]
@allieychen Don't give up so quicky - it's easier than you think.  In `Receiver` what do you see the issue to be - here's the link and below is the code:

https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/common.py#L121-L131

```Python
class Receiver(object):
  """For internal use only; no backwards-compatibility guarantees.
  An object that consumes a WindowedValue.
  This class can be efficiently used to pass values between the
  sdk and worker harnesses.
  """

  def receive(self, windowed_value):
    raise NotImplementedError
```

Basically what do you see missing that you would usually like to have when creating a class in Python?  The `TypeError: object() takes no parameters` is a big hint :)

~p

**Comment by allieychen** [comment]
It seems that [BEAM 4755](https://issues.apache.org/jira/browse/BEAM-4755) has been resolved recently. I think we can just wait till the next version is released.

**Comment by allieychen** [comment]
The issue is filed in [BEAM 5927](https://issues.apache.org/jira/browse/BEAM-5927).

**Comment by allieychen** [comment]
Track the issue in [BEAM 6404](https://issues.apache.org/jira/browse/BEAM-6404).
