### ISSUE TITLE
Native support for bgzip files.

### ISSUE THREAD

**Issue by bashir2** [googlegenomics/gcp-variant-transforms#334]
Currently Variant Transforms accepts some compressed formats (like gzip) as input but the loading cannot be sharded for those files. The [bgzip](http://www.htslib.org/doc/bgzip.html) format is compatible with gzip but is designed to be easy to split into chunks and build indices on top of it with tabix ([this paper describes the details](https://academic.oup.com/bioinformatics/article/27/5/718/262743)).

We should add support for loading indexed bgz files in parallel. This has come up a few times in different contexts (e.g., loading gnomAD) and it seems it is time to prioritize it (for now P3 until prioritization is done).

**Comment by allieychen** [comment]
Done. Related PR: [PR 484](https://github.com/googlegenomics/gcp-variant-transforms/pull/484), [PR 490](https://github.com/googlegenomics/gcp-variant-transforms/pull/490).
