### ISSUE TITLE
Detect empty VCFs since VEP does not

### ISSUE THREAD

**Issue by mbookman** [googlegenomics/gcp-variant-transforms#399]
## Problem

When a VCF is empty, VEP fails with:

```
      -------------------- EXCEPTION --------------------
      MSG: ERROR: Can't detect format

      STACK Bio::EnsEMBL::VEP::Parser::new /opt/variant_effect_predictor/modules/Bio/EnsEMBL/VEP/Parser.pm:140
      STACK Bio::EnsEMBL::VEP::Runner::get_Parser /opt/variant_effect_predictor/modules/Bio/EnsEMBL/VEP/Runner.pm:789
      STACK Bio::EnsEMBL::VEP::Runner::get_InputBuffer /opt/variant_effect_predictor/modules/Bio/EnsEMBL/VEP/Runner.pm:816
      STACK Bio::EnsEMBL::VEP::Runner::init /opt/variant_effect_predictor/modules/Bio/EnsEMBL/VEP/Runner.pm:131
      STACK Bio::EnsEMBL::VEP::Runner::run /opt/variant_effect_predictor/modules/Bio/EnsEMBL/VEP/Runner.pm:194
      STACK toplevel ./vep:222
      Date (localtime)    = Fri Oct 19 22:03:13 2018
      Ensembl API version = 91
      ---------------------------------------------------
```

This has been filed here:

https://github.com/Ensembl/ensembl-vep/issues/215

The current impact on `vcf_to_bq` is that when generating annotations with VEP is enabled, a Pipelines operation will fail with:

```
error:
  code: 9
  message: 'Execution failed: action 5: unexpected exit status 2 was not ignored'
```

and the above message will be observed in the operation event logs.

However, due to #257, this error will currently be ignored. When #257 is fixed then this particular error will cause the `vcf_to_bq` job to fail.

## Workaround

It would be great to detect this in `vcf_to_bq`. Not sure if it is the most efficient way, but this could be trivially determined with something like:

```
readonly LINE_COUNT="$(zcat "${GZIPPED_VCF}" | grep -A 1 "^#CHROM" | wc -l)"
if [[ "${LINE_COUNT}" == "0" ]]; then
  2>&1 echo "Invalid VCF header. #CHROM header not found"
  exit 1
elif [[ "${LINE_COUNT}" == "1" ]]; then
  echo "VCF file contains no variants. Exiting."
  exit 0
fi
```

## Use case

To add a concrete case for this, I ran the Broad's [joint genotyping workflow](https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4.wdl) on a set of more than 1000 samples. The workflow has two paths depending on the number of samples, setting:

```
    Boolean is_small_callset = num_gvcfs <= 1000
```

and subsequent branching in a few places based on that.

Of note is that for more than 1000 samples, the output you get is a set of sharded (gzipped) VCFs, each VCF applying to a different interval in the genome. It turns out that you are likely to have some intervals that don't produce any variants (hard to sequence regions, telomeres, etc.).

**Comment by bashir2** [comment]
Thanks @mbookman for filing these detailed annotation/VEP related issues. I just wanted to point out that we are actively working on improving VEP integration into Variant Transforms and some of these issues will  be automatically resolved once we finish the parallelization effort. I am adding these issues to the [Parellel VEP project](https://github.com/googlegenomics/gcp-variant-transforms/projects/15) to make sure we revisit them once the parallelization effort is done.
