### ISSUE TITLE
FR: Retry gsutil cp operations

### ISSUE THREAD

**Issue by mbookman** [googlegenomics/gcp-variant-transforms#400]
I am running `vcf_to_bq` with `--run_annotation_pipeline` set.
I have 5103 gzipped VCF files which were produced by the Broad's Joint Genotyping workflow.

Some of the annotation steps fail due to transient errors that cause `gsutil cp` to fail.
Since the interactions with GCS depend on fetching the Compute Engine service account credentials from the metadata server, the metadata server failures manifest in a few different errors:

    Failure: Could not reach metadata service: [Errno 111] Connection refused.
    Failure: GCE credentials requested outside a GCE instance.
    ServiceException: 401 Anonymous caller does not have storage.objects.list access to <project-id>

I suggest putting in wrappers around the `gsutil cp` commands added by vep_runner.py
`gsutil` has built-in retries, but there are some conditions that it considers to be a hard-failure and authentication/permissions errors are hard failures. For the Pipelines API v1alpha2 and for `dsub`, before putting in our own retries, we would often see a "low" failure rate (maybe 3%) with jobs due to `gsutil cp` failures. For 100 operations, that meant chasing down 3 failures and retrying; for 1000 operations... 30, etc.

Once we put in the automatic retries those types of failures all but went away.

**Comment by allieychen** [comment]
It is resolved by using the wrapped gsutil in `gcr.io/cloud-genomics-pipelines/io`.
