### ISSUE TITLE
Annotations: make the input VCF an environment variable to make it easier to extract from the operation

### ISSUE THREAD

**Issue by mbookman** [googlegenomics/gcp-variant-transforms#401]
I am running `vcf_to_bq` with `--run_annotation_pipeline` set.
I have 5103 gzipped VCF files which were produced by the Broad's Joint Genotyping workflow.
Some of the annotation steps fail and I'd like to be able to easily get a list of which VCF files I need to re-submit.

Some of the shards that failed were due to VCFs with no variants as described in #399.
The others were some arbitrary transient errors, primarily due to GCE metadata server issues.
Since the interactions with GCS depend on fetching the Compute Engine service account credentials from the metadata server, the metadata server failures manifest in a few different errors:

    Failure: Could not reach metadata service: [Errno 111] Connection refused.
    Failure: GCE credentials requested outside a GCE instance.
    ServiceException: 401 Anonymous caller does not have storage.objects.list access to <project-id>

Worth noting is that for some of my shards the above errors manifested in action 6 (copy output VCF to GCS) and some manifested in action 7 (copy log file to GCS). I could treat those that completed action 6, but not action 7, as "success" since it is the output VCF I need, not the log file.

I think that the above would largely go away with some simple retries as described in #400.
But it would also be nice if I could easily extract the source VCF file. vep_runner.py currently directly formats the "gsutil cp <file>" strings. It would be nice if the VCF file was an environment variable for the operation so that I could more easily extract it from the operation programmatically.

**Comment by allieychen** [comment]
The retires are added in https://github.com/googlegenomics/gcp-variant-transforms/pull/433, those failures are properly handled. Do you think you still need this feature?

**Comment by mbookman** [comment]
Thanks @allieychen . I successfully ran the annotations pipeline again and did not run into any failures, so perhaps the retries are sufficient. I am okay with closing this.
