### ISSUE TITLE
Resolve conflicts in VCF header files

### ISSUE THREAD

**Issue by nmousavi** [googlegenomics/gcp-variant-transforms#49]
Example of resolvable conflicts:

Type:
-  Float vs Integer

Number:
- dot vs 2, 3, ...
- R, G vs 2, 3, ...
- A vs dot (only if flag split_alternate_allele_info_fields is off)

....

**Comment by nmousavi** [comment]
Type and number conflicts (mentioned above) are fixed in pulls:

#39  
#41 
#47 
#50 
#54

@arostamianfar : is there anything left?

**Comment by arostamianfar** [comment]
Thanks, Nima! This is great!
As discussed, please file a separate issue for resolving "." and "A" when `--split_alternate_allele_info_fields` is true as that's a lower priority task. You may close this one.

**Comment by nmousavi** [comment]
Thanks Asha! Closing this and created a new lower priority one.
