### ISSUE TITLE
VCF Reader

### ISSUE THREAD

**Issue by Rokshan2016** [googlegenomics/gcp-variant-transforms#537]
@samanvp Hi, is there any tool that can be used as VCF reader in gcp ? Or something that can generate visual report out of VCF

**Comment by samanvp** [comment]
Hi @Rokshan2016 
[Variant Transforms](https://github.com/googlegenomics/gcp-variant-transforms) is our VCF readers tool that receives VCF files are input and produces BigQuery tables as output. Under the hood it uses [Pysam](https://github.com/pysam-developers/pysam) for parsing VCF files and utilizes [Apache Beam](https://beam.apache.org/) to run thousands of processes in parallel. Using Variant Transforms we are able to read all [1000Genome](https://www.internationalgenome.org/) samples (~800GB) in less than an hour.

As soon as you import your VCF files into BigQuery you will be able to easily study your data: using SQL queries you can filter, sort, and export your data to spreadsheets or CSV files an then use your preferred visualization/analysis tool (Python, R, IGV, ...) to explore the exported data. 

Variant Transforms also has a BigQuery to VCF component that lets you export your BigQuery tables back to VCF. This is very useful in case you want to study a subset of variants which can be easily filtered by SQL queries.

Please let us know if you need any help with running Variant Transforms and/or running queries on your BigQuery tables.

**Comment by Rokshan2016** [comment]
@samanvp Thanks!  

We have a use case where we can read vcf file from GCS/Big Query and export the sequence data in FHIR Server for a specific Patient. http://hl7.org/fhir/2018Sep/sequence.html
But I am not understanding how can we link vcf data from gcs / big query for a certain Patient ?

**Comment by samanvp** [comment]
I think these are things you need to do:
* Copy your VCF files into a GCS bucket.
* Run Variant Transforms to [load your VCF files to a BigQuery table](https://github.com/googlegenomics/gcp-variant-transforms#loading-vcf-files-to-bigquery).
* Run a query similar to `SELECT * FROM my_table WHERE call_name='particular_sample'` (I abstracted away some details here) and write the output of that query into another BigQuery table.
* Run [bq_to_vcf](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/bigquery_to_vcf.md) to convert the resulting BigQuery table into a VCF file.
* VCF file will be available in the GCS bucket you determined in the last stage.

I hope these explanations are a good starting point for you. Please let me know if we can help with anything else.

**Comment by Rokshan2016** [comment]
@samanvp 
I have successfully done all of this . What I was saying in the BigQuery Schema  there is no cloumn where it mentioned Patient id . How can we understand which Patient variant information it is ?                                                      https://bigquery.cloud.google.com/table/bigquery-public-data:human_genome_variants.1000_genomes_phase_3_variants_20150220

**Comment by Rokshan2016** [comment]
@samanvp  I think I get what you are saying , call name represents Patient id . I will try that . Thanks !.  Closing this :)

**Comment by samanvp** [comment]
The details that I abstracted out is exactly what you needed, most likely you need to flatten your table to create `call_name` column. Please refer to [this page](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/flattening_table.md#flattening-basics) which has all the details of how to flatten a table.

Sorry if I was very verbose and I didn't address you main point.
Again please do not hesitate to contact us if you need help with anything.
