### ISSUE TITLE
DataFlow suggestion 

### ISSUE THREAD

**Issue by Rokshan2016** [googlegenomics/gcp-variant-transforms#570]
@samanvp 

Hi , I  am trying to create a dataflow template where it needs to write in two tables sequentially in bigquery.

e.g First it writes in "Patient" table. Ones its done then it writes in "Statistics" table.  But I am facing this issue  - once it writes in Patient table , it does not execution any code after that.

If you can please give some suggestion , it will be really helpful.

Thanks!

**Comment by samanvp** [comment]
Hi @Rokshan2016 
As far as I know, you should be able to write a PCollection to multiple output tables. As an example take a look at this line in VaraintTransforms (sorry, I couldn't find a better example):
https://github.com/googlegenomics/gcp-variant-transforms/blob/ac25684e2fb6d9fa36bddd8be2b2cf41a728ceb1/gcp_variant_transforms/vcf_to_bq.py#L492

`variants[i]` is a PCollection which is being sent to `variant_to_avro.VariantToAvroFiles`. You could repeat this process twice and write them to two different destination files. I don't see any reason why you cannot do the same thing with `WriteToBigQuery` [transform](https://github.com/apache/beam/blob/0edd1e12e14ffca8d3bdccd8dbe05f8c592aea64/sdks/python/apache_beam/io/gcp/bigquery.py#L1221). Take a look at #449 to see how you can use `WriteToBigQuery` transform.

Alternatively, you could use AVRO files as another mean to achieve the same goal, basically you write your PCollection into AVRO files using `WriteToAvro` transform and then you can load them to multiple BQ tables using BQ API or `bq load ... ` CLI command. This is what we did in #558. Take a look at [this comment](https://github.com/googlegenomics/gcp-variant-transforms/pull/568#issuecomment-603623989) to see why we decided to make this change.

I am closing this issue but please feel free to continue the conversation if you need help with this.
