### ISSUE TITLE
Failed Precondition error

### ISSUE THREAD

**Issue by marcelokauffman** [googlegenomics/gcp-variant-transforms#591]
I am getting this type of errors during my running of vcf to bq: 

unexpected exit status 1 was not ignored (re
ason: FAILED_PRECONDITION)

What do you think is the reason?

**Comment by marcelokauffman** [comment]
19:29:04 Unexpected exit status 1 while running "-c /opt/gcp_variant_transforms/bin/vcf_to_bq --input_pattern gs://genomics-public-data/NA12878.chr20.sample.DeepVariant-0.7.2
.vcf --output_table prueba-cloud-life:VCS_prueba_cloud_life.41967_2 --temp_location gs://prueba-cloud-life-life-sciences/temp --job_name vcf-to-bigquery --runner DataflowRunn
er --project prueba-cloud-life"
19:29:04 Started running "-c gsutil -q cp /google/logs/output ''/runner_logs_20200430_192636.log"
19:29:11 Stopped running "-c gsutil -q cp /google/logs/output ''/runner_logs_20200430_192636.log"
19:29:11 Execution failed: generic::failed_precondition: while running "-c /opt/gcp_variant_transforms/bin/vcf_to_bq --input_pattern gs://genomics-public-data/NA12878.chr20.s
ample.DeepVariant-0.7.2.vcf --output_table prueba-cloud-life:VCS_prueba_cloud_life.41967_2 --temp_location gs://prueba-cloud-life-life-sciences/temp --job_name vcf-to-bigquer
y --runner DataflowRunner --project prueba-cloud-life": unexpected exit status 1 was not ignored
19:29:12 Worker released

**Comment by samanvp** [comment]
Could you please share the runner logs (`runner_logs_20200430_192636.log`) with us? I will be copied to your temp directory:
```
gs://prueba-cloud-life-life-sciences/temp/logs/vcf-to-bigquery/runner_logs_20200430_192636.log
```

**Comment by marcelokauffman** [comment]
It finally worked, the error was on my side, sorry.

**Comment by samanvp** [comment]
Good to hear, please let us know if you need help with Variant Transforms.
