### ISSUE TITLE
Job fails on 1000Genome dataset with "No such field: call.FT."

### ISSUE THREAD

**Issue by nmousavi** [googlegenomics/gcp-variant-transforms#61]
Possibilities:

1 ) field FT is missing in the dataset
2) field FT is present in the dataset, but there is a bug in merge headers logic

**Comment by nmousavi** [comment]
Confirmed field FT is missing in the dataset headers (1). Next step: find the file(s) containing this field.

**Comment by arostamianfar** [comment]
The field is coming from a small (430kb) file: gs://genomics-public-data/1000-genomes/vcf/ALL.chrY.genome_strip_hq.20101123.svs.low_coverage.genotypes.vcf

We can ignore this in our import for now by specifying `--input_pattern gs://genomics-public-data/1000-genomes/vcf/ALL*phase1*vcf` 

Longer term, we are planning to provide a more generic solution for this in Issue #101

**Comment by nmousavi** [comment]
PR##114 solves the issue with missing fields but 1000genome dataset is still not convertible. The reason is that field HOMSEQ is defined as repeated ('.') in the header, but appeared with no value in some variants which is converted to FLAG by pyvcf, and hence incompatible type.

##INFO=<ID=HOMSEQ,Number=.,Type=String,Description="Sequence of base pair identical micro-homology at event breakpoints">

CIEND=-17,33;CIPOS=-18,19;END=3111352;HOMLEN=0;HOMSEQ;SOURCE=GenomeStrip_3109317_3111355;SVLEN=-2034;SVTYPE=DEL	GT:FT:GL:GQ	0:PASS:0.00,-39.73:99
