### ISSUE TITLE
Scaling to ~1000 samples fails

### ISSUE THREAD

**Issue by samesense** [googlegenomics/gcp-variant-transforms#618]
Release v0.8.1 runs fine w/ 10 or 100 vcf files, but cannot handle 1000 at a time.

**Comment by samanvp** [comment]
Hi @samesense 
Sorry for inconvenience, we are getting ready to release v0.9.0 very soon. It's a major update with many new features, such as much better handling of large input sizes and 5x-30x query cost reduction. I highly recommend **not** to process a big batch using the current Variant Transforms latest image.

If you are willing to try our release candidate image please send me and email at `samanvp [at] google [dot] com` and I will share with you our release candidate. Alternatively, you could wait for another week or two to use the new release when it's publicly available.

Best,
