### ISSUE TITLE
Add a flag to specify the "pipeline mode" (SMALL, MEDIUM, or LARGE)

### ISSUE THREAD

**Issue by mbookman** [googlegenomics/gcp-variant-transforms#659]
`pipeline_common.py` has some logic for figuring out the "pipeline mode":

```
# If the # of files matching the input file_pattern exceeds this value, then
# headers will be merged in beam.
_SMALL_DATA_THRESHOLD = 100
_LARGE_DATA_THRESHOLD = 50000

...

def get_pipeline_mode(all_patterns):
  ...
  if len(all_patterns) > 1:
    return PipelineModes.LARGE

  match_results = filesystems.FileSystems.match(all_patterns)
  if not match_results:
    raise ValueError(
        'No files matched input_pattern: {}'.format(all_patterns[0]))

  total_files = len(match_results[0].metadata_list)

  if total_files > _LARGE_DATA_THRESHOLD:
    return PipelineModes.LARGE
  elif total_files > _SMALL_DATA_THRESHOLD:
    return PipelineModes.MEDIUM
  return PipelineModes.SMALL
```

for some of our loads, it didn't trigger `PipelineModes.LARGE` and we needed it to. Even for a load of 1000 files, we were running into the error:

> Error message from worker: Total size of the BoundedSource objects returned by BoundedSource.split() operation is larger than the allowable limit. For more information, please check the corresponding FAQ entry at https://cloud.google.com/dataflow/pipelines/troubleshooting-your-pipeline.

I went in and hard-coded `get_pipeline_mode()`:

```
  logging.info("Forcing PipelinesModes.Large")
  return PipelineModes.LARGE
```

and the workflows were able to run to completion (after building a custom docker image, pushing to GCR, updating our docker run command to pick up the custom image).

There used to be a flag `--optimize_for_large_inputs` which could force this. It might be nice to simply add a flag `--pipeline-mode` which could take values `small`, `medium`, or `large`, along with some explanation of what code paths they trigger and guidance on when to use each. Note that it isn't clear to me whether there were any code paths that differentiated SMALL versus MEDIUM.

**Comment by lawrenae** [comment]
@mbookman do you have an example configuration you could share where you'd expect `PipelineModes.LARGE` but didnt get it? I'm struggling to understand the exact scenario.

**Comment by pgrosu** [comment]
Hi Andy (@lawrenae),

Matt might be referring to the idea that not all files are the same size.  So you could have fewer very large files, thus returning PipelineModes.SMALL or PipelineModes.MEDIUM -- given the file count -- when it should be returning PipelineModes.LARGE.  Those same large files if they were split into many smaller ones would trigger a proper PipelineModes.LARGE response.

Matt might have a better example.

Hope it helps,
~p

**Comment by mbookman** [comment]
@pgrosu is spot on.

When running the Broad Institute's joint discovery workflow (for AMP PD) as can be found here:

https://github.com/amp-pd/amp-pd-workflows/tree/master/wgs/joint-discovery

the output is a large number of sharded VCFs, though the number of VCFs never approached 50,000. The largest was just over 20,000.

The key point though is that as we increased the number of input samples over the different releases for AMP PD (release 1 around 4,000 samples and release 2 around 10,000), the size of the output VCFs increased.

So the number of files is a poor heuristic for determining "small", "medium", and "large" categories.

**Comment by lawrenae** [comment]
I dont currently understand how well the number of files logic is working for others, despite it obviously not being a good way to determine the proper mode. Thus,  I'm concerned about removing that functionality because it'd be a breaking change for users that happen to get LARGE mode today (they'd now be required to specify it). How about leaving the existing logic and then just allow this flag to override it, if specified? 

That said, removing the MEDIUM enum seems fine, and I wonder if there's a valid case for forcing SMALL where LARGE would have been dynamically chosen otherwise. If there is, then my preference would be to use `--pipeline_mode` and allow folks to specify whatever mode

**Comment by pgrosu** [comment]
Hi Andy (@lawrenae),

The thing is that `pipeline_mode` is used in several scenarios (reading variants, merging headers, etc).  Thus if after reading the initial files -- which might require a large pipeline -- the filters would filter out most of the low quality data, then subsequently a small pipeline would be more optimal for the rest of the processed data.  The code should be scalable to the incoming information, and thus turning `gcp-variant-transforms` into a first-class function to be used in larger workflows.

The good news is that you could have the best of both worlds.  You can keep everything as it is based on the current customers needs, and just add another flag that says `--enable_adaptable_pipelines`, where then at key portions of the code-base the code self-checks the actual size of the next input data to be processed and auto-adjusts the pipeline size accordingly.  Then the code truly becomes scalable to the data.

Hope it helps,
~p
