### ISSUE TITLE
Add proper release process and versioning

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#77]
Ensure both github and docker images have proper release process (includes running integration tests) and are versioned appropriately.

**Comment by bashir2** [comment]
A note related to this: Issue #62 is done which means that every git commit will automatically undergo image building and integration tests (against that image); that should make the release process of this issue, simpler.

Of course, we need to extend the current integration tests (e.g., add a big public data set to test cases and do more validations of the output tables) if we want to move towards a "push on green" process.
