### ISSUE TITLE
Add native annotation support

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#81]
This task is to add native annotation support (e.g. gene ID, variant harmfulness, clinvar, dbSNP, etc) as part of the VCF->BigQuery pipeline.

Initially, we can have a pre-processing step that adds [VEP](https://useast.ensembl.org/info/docs/tools/vep/index.html) or [SnpEff](http://snpeff.sourceforge.net/SnpEff_manual.html) annotations to the VCF file prior to import. The annotations would be added to a new INFO field that can then be parsed to load each annotation as a separate column to BigQuery. The annotation field presumably follows [this schema](http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf).

Having a more generic INFO parser will also be beneficial for other pre-annotated VCF files such as [gnomAD](http://gnomad.broadinstitute.org/).

We can integrate [Verily's annotation pipeline](https://github.com/verilylifesciences/variant-annotation) to load annotations via VEP.

Note: adding annotations as part of the pipeline without pre-processing is outside the scope of this task. We can consider that option if the pre-processing step is not feasible for certain use cases.

**Comment by bashir2** [comment]
We can now close this super-issue as the original goal is achieved: We can (i) properly parse annotation fields and (ii) run VEP as a preprocess step of VT; this is fully integrated with VT and only needs supplying some flags.

Other remaining issues like documentation/integration-test/refactoring have their own tracking issues. The ones targeted for Q2 are under [this project](https://github.com/googlegenomics/gcp-variant-transforms/projects/3).
