### ISSUE TITLE
Add a "decompress and load" option 

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#91]
Even though the pipeline supports files in gzip and bzip2 formats, such files cannot be sharded. There are also other compression formats such as bgzip (http://www.htslib.org/doc/tabix.html) that are not supported.

It would be ideal to provide a "decompress and load" option as part of the pipeline. We can use the Pipelines API to do this in a scalable manner.

**Comment by allieychen** [comment]
Done. Related PR: [PR 484](https://github.com/googlegenomics/gcp-variant-transforms/pull/484), [PR 490](https://github.com/googlegenomics/gcp-variant-transforms/pull/490).
