### ISSUE TITLE
Desirable enhancements of the continuous integration.

### ISSUE THREAD

**Issue by bashir2** [googlegenomics/gcp-variant-transforms#98]
Background: Issue #62.

* It would be nice to force an integration test run by Travis, when a pull request is sent. One issue is credentials to access Google Cloud projects by Travis. [This tutorial](https://cloud.google.com/solutions/continuous-delivery-with-travis-ci) might help.

* Upon a commit, if the continuous integration build/test fails, no notification is currently sent. One should look at the "Build history" portion of the Container Registry dashboard for project `gcp-variant-transforms-test` to check if CI for that commit succeeded or not. There is a Pub/Sub channel created for the CI and it can be used to set up such notifications (details [here](https://cloud.google.com/container-builder/docs/configure-third-party-notifications)).

**Comment by arostamianfar** [comment]
Closing this b/c:
- We can use native CloudBuild + GitHub integration to run our integration tests as part of presubmit; see #332 
- We have solved the notification-on-failure issue already through an internal framework.
