### ISSUE TITLE
Create large integration tests.

### ISSUE THREAD

**Issue by bashir2** [googlegenomics/gcp-variant-transforms#99]
The current integration tests we have are small and do not cover enough variations in VCF inputs. To automate our release process, we need to add larger cases and do both deeper validation and performance analysis to make sure we are not introducing any regression. One potential dataset to use is 1000 Genomes (see Issue #61 too).

**Comment by arostamianfar** [comment]
A few additional notes:
- I think we should have a 'large' test based on Platinum Genomes (`gs://genomics-public-data/platinum-genomes/vcf/*.vcf`) that runs on every submit. It takes about 15mins (with merging) on 64x8-core machines.
- 1000 genome data would be 'huge' and we'd only run it on a release candidate. By default, the integration test framework should ignore 'huge' tests.
- We should also test with a large number of small files (e.g. copy valid-4.2.vcf many times). This is to test the 3 main 'modes' of the pipeline: SMALL (already tested), MEDIUM (need to copy the file 100+ times), and LARGE (50k+ files). These should also run pretty quickly (<20mins) with a reasonable number of machines.

**Comment by arostamianfar** [comment]
FYI, bumping this to P1 together with Issue #106 (I'd say Issue #106 is P1.5 though :p ). I'm still a bit concerned that we don't have enough integration testing coverage as we build new features.
